package com.FinalYearProject.FinalYearProject.Service;


import com.FinalYearProject.FinalYearProject.Domain.Question;
import com.FinalYearProject.FinalYearProject.Domain.QuestionPaper;
import com.FinalYearProject.FinalYearProject.Domain.User;
import com.FinalYearProject.FinalYearProject.Exceptions.QuestionPaperException.DuplicateQuestionPaperException;
import com.FinalYearProject.FinalYearProject.Exceptions.QuestionPaperException.QuestionPaperNotFoundException;
import com.FinalYearProject.FinalYearProject.Exceptions.UserEeceptions.UserNotAuthorizesException;
import com.FinalYearProject.FinalYearProject.Repository.QuestionPaperRepository;
import com.FinalYearProject.FinalYearProject.Util.QuestionPaperUtil;
import com.FinalYearProject.FinalYearProject.Util.UserUtil;
import org.apache.coyote.BadRequestException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.Comparator;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

@Service
//TODO check if user is super visor
public class QuestionPaperService {
    @Autowired
    private QuestionPaperRepository questionPaperRepository;
    @Autowired
    private UserService userService;
    @Autowired
    private QuestionService questionService;

    public List<QuestionPaper> getAllQuestionPapers(){
        List<QuestionPaper> questionPapers=questionPaperRepository.findAll();
        if (questionPapers.isEmpty()){
            throw new QuestionPaperNotFoundException("no question paper in db");
        }
        else {
            return questionPapers;
        }
    }

    public Page<QuestionPaper> getAllQuestionPapers(int pageNo , int size){
        Pageable pageable=PageRequest.of(pageNo,size);
        Page<QuestionPaper> questionPaperPage=questionPaperRepository.findAll(pageable);
        if (!(questionPaperPage.isEmpty())){
            return questionPaperPage;
        }
        else {
            throw new QuestionPaperNotFoundException("no question paper in db ");
        }
    }

    public QuestionPaper findById(Long Id){
        return questionPaperRepository.findById(Id)
                .orElseThrow(()-> new QuestionPaperNotFoundException("no question paper with id"+Id));
    }

    public QuestionPaper findByExamTitle(String examTitle) {
        return questionPaperRepository.findByExamTitle(examTitle)
                .orElseThrow(()-> new QuestionPaperNotFoundException("no question paper with exam title"+examTitle));
    }

    public List<QuestionPaper> findByGeneratedByUsingEmail(String email){
        User user=userService.findByEmail(email);
        List<QuestionPaper> questionPapersGeneratedByUser=questionPaperRepository.findByGeneratedBy(user);
        if (questionPapersGeneratedByUser.isEmpty()){
            throw new QuestionPaperNotFoundException("no question paper has been generated by user with email "+email);
        }
        else {
            return questionPapersGeneratedByUser;
        }
    }

    public Page<QuestionPaper> findByGeneratedByUsingEmail(String email, int pageNo, int size){
        User user=userService.findByEmail(email);
        Pageable pageable= PageRequest.of(pageNo,size);
        Page<QuestionPaper> questionPapersGeneratedByUser=questionPaperRepository.findByGeneratedBy(user,pageable);
        if (!(questionPapersGeneratedByUser.isEmpty())){
            return questionPapersGeneratedByUser;
        }
        else {
            throw new QuestionPaperNotFoundException("no question paper has been generated by user with email "+email);
        }
    }

    public List<QuestionPaper> findByGeneratedByUsingId(Long Id){
        User user=userService.findUserById(Id);
        List<QuestionPaper> questionPapers=questionPaperRepository.findByGeneratedBy(user);
        if (questionPapers.isEmpty()){
            throw new QuestionPaperNotFoundException("no question paper has been generated by user with Id "+Id);
        }
        else {
            return questionPapers;
        }
    }

    public Page<QuestionPaper> findByGeneratedByUsingId(Long Id,int pageNo,int size){
        Pageable pageable=PageRequest.of(pageNo,size);
        User user=userService.findUserById(Id);
        Page<QuestionPaper> questionPapers=questionPaperRepository.findByGeneratedBy(user,pageable);
        if (!(questionPapers.isEmpty())){
            return questionPapers;
        }
        else {
            throw new QuestionPaperNotFoundException("no question paper has been generated by user with Id "+Id);
        }
    }

    public List<QuestionPaper> findByApprovedByUsingEmail(String email){
        User user=userService.findByEmail(email);
        List<QuestionPaper> questionPapers=questionPaperRepository.findByApprovedBy(user);
        if (questionPapers.isEmpty()){
            throw new QuestionPaperNotFoundException("no question paper has been generated by user with email "+email);
        }
        else {
            return questionPapers;
        }
    }

    public  Page<QuestionPaper> findByApprovedByUsingEmail(String email, int pageNo , int size){
        Pageable pageable=PageRequest.of(pageNo,size);
        User user=userService.findByEmail(email);
        Page<QuestionPaper> questionPapers=questionPaperRepository.findByApprovedBy(user,pageable);
        if (!(questionPapers.isEmpty())){
            return questionPapers;
        }
        else {
            throw new QuestionPaperNotFoundException("no question paper has been generated by user with email "+email);

        }
    }

    public List<QuestionPaper> findByApprovedByUsingId(Long Id){
        User user=userService.findUserById(Id);
        List<QuestionPaper> questionPapers=questionPaperRepository.findByApprovedBy(user);
        if (questionPapers.isEmpty()){
            throw new QuestionPaperNotFoundException("no question paper has been generated by user with Id "+Id);
        }
        else {
            return questionPapers;
        }
    }

    public Page<QuestionPaper> findByApprovedByUsingId(Long Id,int pageNo,int size){
        Pageable pageable=PageRequest.of(pageNo,size);
        User user=userService.findUserById(Id);
        Page<QuestionPaper> questionPapers=questionPaperRepository.findByApprovedBy(user,pageable);
        if (!(questionPapers.isEmpty())){
            return questionPapers;
        }
        else {
            throw new QuestionPaperNotFoundException("no question paper has been generated by user with Id "+Id);
        }
    }

    public List<QuestionPaper> findApproved(){
        List<QuestionPaper> questionPapers=questionPaperRepository.findByApproved(Boolean.TRUE);
        if (questionPapers.isEmpty()){
            throw new QuestionPaperNotFoundException("no question paper has been approved yet ");
        }
        else {
            return questionPapers;
        }
    }

    public Page<QuestionPaper> findApproved(int pageNo,int size){
        Pageable pageable=PageRequest.of(pageNo,size);
        Page<QuestionPaper> questionPapers=questionPaperRepository.findByApproved(Boolean.TRUE,pageable);
        if (!(questionPapers.isEmpty())){
            return questionPapers;
        }
        else {
            throw new QuestionPaperNotFoundException("no question paper has been approved yet ");
        }
    }

    public List<QuestionPaper> findNotApproved(){
        List<QuestionPaper> questionPapers=questionPaperRepository.findByApproved(Boolean.FALSE);
        if (questionPapers.isEmpty()){
            throw new QuestionPaperNotFoundException("no question paper has been left to approve");
        }
        else {
            return questionPapers;
        }
    }

    public Page<QuestionPaper> findNotApproved(int pageNo,int size){
        Pageable pageable=PageRequest.of(pageNo,size);
        Page<QuestionPaper> questionPapers=questionPaperRepository.findByApproved(Boolean.FALSE,pageable);
        if (!(questionPapers.isEmpty())){
            return questionPapers;
        }
        else {
            throw new QuestionPaperNotFoundException("no question paper has been approved yet ");
        }
    }

    @Transactional
    public QuestionPaper approveQuestionPaperById(Long id){
        String userEmail=UserUtil.getUserAuthentication().getUsername();
        User user=userService.findByEmail(userEmail);
        if (!(user.getRole().contains("ROLE_SUPERVISOR"))){
            throw new UserNotAuthorizesException("User not Authorized to make this request");
        }
        else {
           QuestionPaper questionPaper=questionPaperRepository
                   .findById(id)
                   .orElseThrow(
                           ()-> new QuestionPaperNotFoundException("no Question Paper with id :" +id)
                   );
           if (questionPaper.getApproved().equals(Boolean.TRUE)){
               return questionPaper;
           }
           else {
               questionPaper.setApproved(Boolean.TRUE);
               questionPaper.setApprovedBy(user);
               questionPaperRepository.save(questionPaper);
               return questionPaper;
           }
        }
    }

    @Transactional
    public QuestionPaper notApproveQuestionPaperById(Long id){
        String userEmail=UserUtil.getUserAuthentication().getUsername();
        User user=userService.findByEmail(userEmail);
        if (!(user.getRole().contains("ROLE_SUPERVISOR"))){
            throw new UserNotAuthorizesException("User not Authorized to make this request");
        }
        else {
            QuestionPaper questionPaper=questionPaperRepository
                    .findById(id)
                    .orElseThrow(
                            ()-> new QuestionPaperNotFoundException("no Question Paper with id :" +id)
                    );
            if (questionPaper.getApproved().equals(Boolean.FALSE)){
                return questionPaper;
            }
            else {
                questionPaper.setApproved(Boolean.FALSE);
                questionPaper.setApprovedBy(user);
                questionPaperRepository.save(questionPaper);
                return questionPaper;
            }
        }
    }

    @Transactional
    public QuestionPaper approvedQuestionPaperByTile(String examTitle){
        String userEmail=UserUtil.getUserAuthentication().getUsername();
        User user=userService.findByEmail(userEmail);
        if (!(user.getRole().contains("ROLE_SUPERVISOR"))){
            throw new UserNotAuthorizesException("User not Authorized to make this request");
        }
        else {
            QuestionPaper questionPaper = questionPaperRepository
                    .findByExamTitle(examTitle)
                    .orElseThrow(
                            ()-> new QuestionPaperNotFoundException("question paper with title :"+examTitle+" does not exist ")
                    );
            if (questionPaper.getApproved().equals(Boolean.TRUE)){
                return questionPaper;
            }
            else {
                questionPaper.setApproved(Boolean.TRUE);
                questionPaper.setApprovedBy(user);
                questionPaperRepository.save(questionPaper);
                return questionPaper;
            }
        }
    }

    @Transactional
    public QuestionPaper notApprovedQuestionPaperByTile(String examTitle){
        String userEmail=UserUtil.getUserAuthentication().getUsername();
        User user=userService.findByEmail(userEmail);
        if (!(user.getRole().contains("ROLE_SUPERVISOR"))){
            throw new UserNotAuthorizesException("User not Authorized to make this request");
        }
        else {
            QuestionPaper questionPaper = questionPaperRepository
                    .findByExamTitle(examTitle)
                    .orElseThrow(
                            ()-> new QuestionPaperNotFoundException("question paper with title :"+examTitle+" does not exist ")
                    );
            if (questionPaper.getApproved().equals(Boolean.FALSE)){
                return questionPaper;
            }
            else {
                questionPaper.setApproved(Boolean.FALSE);
                questionPaper.setApprovedBy(user);
                questionPaperRepository.save(questionPaper);
                return questionPaper;
            }
        }
    }

    @Transactional
    public QuestionPaper addQuestionPaper(QuestionPaper questionPaper) throws BadRequestException{
        String email = UserUtil.getUserAuthentication().getUsername();
        User user = userService.findByEmail(email);
        List<Long>Ids=questionPaper.getListOfQuestion()
                .stream()
                .sorted(Comparator.comparing(Question::getId))
                .map(Question::getId)
                .toList();
        String questionPaperFingerprint;
        Set<Question> questions;
        if (!user.getRole().equals("ROLE_TEACHER")){
            throw new UserNotAuthorizesException("User not Authorizes to make this request");
        }
        else {
            questions= new HashSet<>(questionService.getQuestionByIds(Ids));
            if (!(Ids.size()==questions.size())){
                throw new BadRequestException("there are a few band questions");
            }
            else {
                questionPaperFingerprint = QuestionPaperUtil.sha256FingerPrintUsingIds(Ids);
                if (questionPaperRepository.existsByQuestionPaperFingerprint(questionPaperFingerprint)) {
                    throw new DuplicateQuestionPaperException("one more question paper with exact questions exists");
                } else {
                    questionPaper.setListOfQuestion(questions);
                    questionPaper.setGeneratedBy(user);
                    questionPaper.setApproved(Boolean.FALSE);
                    questionPaper.setQuestionPaperFingerprint(questionPaperFingerprint);
                    questionPaperRepository.save(questionPaper);
                }
            }
        }
        return questionPaper;
    }

}