package com.FinalYearProject.FinalYearProject.Service;


import com.FinalYearProject.FinalYearProject.Domain.Question;
import com.FinalYearProject.FinalYearProject.Domain.QuestionPaper;
import com.FinalYearProject.FinalYearProject.Domain.User;
import com.FinalYearProject.FinalYearProject.Exceptions.QuestionPaperException.DuplicateQuestionPaperException;
import com.FinalYearProject.FinalYearProject.Exceptions.QuestionPaperException.QuestionPaperNotFoundException;
import com.FinalYearProject.FinalYearProject.Exceptions.UserEeceptions.UserNotAuthorizesException;
import com.FinalYearProject.FinalYearProject.Repository.QuestionPaperRepository;
import com.FinalYearProject.FinalYearProject.Util.QuestionPaperUtil;
import com.FinalYearProject.FinalYearProject.Util.UserUtil;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Pageable;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.stereotype.Service;

import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.Comparator;
import java.util.List;
import java.util.Set;

@Service
public class QuestionPaperService {
    @Autowired
    private QuestionPaperRepository questionPaperRepository;
    @Autowired
    private UserService userService;

    private List<QuestionPaper> getAllQuestionPapers(){
        List<QuestionPaper> questionPapers=questionPaperRepository.findAll();
        if (questionPapers.isEmpty()){
            throw new QuestionPaperNotFoundException("no question paper in db");
        }
        else {
            return questionPapers;
        }
    }

    public QuestionPaper findById(Long Id){
        return questionPaperRepository.findById(Id)
                .orElseThrow(()-> new QuestionPaperNotFoundException("no question paper with id"+Id));
    }

    public QuestionPaper findByExamTitle(String examTitle) {
        return questionPaperRepository.findByExamTitle(examTitle)
                .orElseThrow(()-> new QuestionPaperNotFoundException("no question paper with exam title"+examTitle));
    }

    public List<QuestionPaper> findByGeneratedByUsingEmail(String email){
        User user=userService.findByEmail(email);
        List<QuestionPaper> questionPapersGeneratedByUser=questionPaperRepository.findByGeneratedBy(user);
        if (questionPapersGeneratedByUser.isEmpty()){
            throw new QuestionPaperNotFoundException("no question paper has been generated by user with email "+email);
        }
        else {
            return questionPapersGeneratedByUser;
        }
    }

    public Page<QuestionPaper> findByGeneratedByUsingEmail(String email, int pageNo, int size){
        User user=userService.findByEmail(email);
        Pageable pageable= PageRequest.of(pageNo,size);
        Page<QuestionPaper> questionPapersGeneratedByUser=questionPaperRepository.findByGeneratedBy(user,pageable);
        if (!(questionPapersGeneratedByUser.isEmpty())){
            return questionPapersGeneratedByUser;
        }
        else {
            throw new QuestionPaperNotFoundException("no question paper has been generated by user with email "+email);
        }
    }

    public List<QuestionPaper> findByGeneratedByUsingId(Long Id){
        User user=userService.findUserById(Id);
        List<QuestionPaper> questionPapers=questionPaperRepository.findByGeneratedBy(user);
        if (questionPapers.isEmpty()){
            throw new QuestionPaperNotFoundException("no question paper has been generated by user with Id "+Id);
        }
        else {
            return questionPapers;
        }
    }

    public Page<QuestionPaper> findByGeneratedByUsingId(Long Id,int pageNo,int size){
        Pageable pageable=PageRequest.of(pageNo,size);
        User user=userService.findUserById(Id);
        Page<QuestionPaper> questionPapers=questionPaperRepository.findByGeneratedBy(user,pageable);
        if (!(questionPapers.isEmpty())){
            return questionPapers;
        }
        else {
            throw new QuestionPaperNotFoundException("no question paper has been generated by user with Id "+Id);
        }
    }

    public List<QuestionPaper> findByApprovedByUsingEmail(String email){
        User user=userService.findByEmail(email);
        List<QuestionPaper> questionPapers=questionPaperRepository.findByApprovedBy(user);
        if (questionPapers.isEmpty()){
            throw new QuestionPaperNotFoundException("no question paper has been generated by user with email "+email);
        }
        else {
            return questionPapers;
        }
    }

    public  Page<QuestionPaper> findByApprovedByUsingEmail(String email, int pageNo , int size){
        Pageable pageable=PageRequest.of(pageNo,size);
        User user=userService.findByEmail(email);
        Page<QuestionPaper> questionPapers=questionPaperRepository.findByApprovedBy(user,pageable);
        if (!(questionPapers.isEmpty())){
            return questionPapers;
        }
        else {
            throw new QuestionPaperNotFoundException("no question paper has been generated by user with email "+email);

        }
    }

    public List<QuestionPaper> findByApprovedByUsingId(Long Id){
        User user=userService.findUserById(Id);
        List<QuestionPaper> questionPapers=questionPaperRepository.findByApprovedBy(user);
        if (questionPapers.isEmpty()){
            throw new QuestionPaperNotFoundException("no question paper has been generated by user with Id "+Id);
        }
        else {
            return questionPapers;
        }
    }

    public Page<QuestionPaper> findByApprovedByUsingId(Long Id,int pageNo,int size){
        Pageable pageable=PageRequest.of(pageNo,size);
        User user=userService.findUserById(Id);
        Page<QuestionPaper> questionPapers=questionPaperRepository.findByApprovedBy(user,pageable);
        if (!(questionPapers.isEmpty())){
            return questionPapers;
        }
        else {
            throw new QuestionPaperNotFoundException("no question paper has been generated by user with Id "+Id);
        }
    }

    public List<QuestionPaper> findApproved(){
        List<QuestionPaper> questionPapers=questionPaperRepository.findByApproved(Boolean.TRUE);
        if (questionPapers.isEmpty()){
            throw new QuestionPaperNotFoundException("no question paper has been approved yet ");
        }
        else {
            return questionPapers;
        }
    }

    public Page<QuestionPaper> findApproved(int pageNo,int size){
        Pageable pageable=PageRequest.of(pageNo,size);
        Page<QuestionPaper> questionPapers=questionPaperRepository.findByApproved(Boolean.TRUE,pageable);
        if (!(questionPapers.isEmpty())){
            return questionPapers;
        }
        else {
            throw new QuestionPaperNotFoundException("no question paper has been approved yet ");
        }
    }

    public List<QuestionPaper> findNotApproved(){
        List<QuestionPaper> questionPapers=questionPaperRepository.findByApproved(Boolean.FALSE);
        if (questionPapers.isEmpty()){
            throw new QuestionPaperNotFoundException("no question paper has been left to approve");
        }
        else {
            return questionPapers;
        }
    }

    public Page<QuestionPaper> findNotApproved(int pageNo,int size){
        Pageable pageable=PageRequest.of(pageNo,size);
        Page<QuestionPaper> questionPapers=questionPaperRepository.findByApproved(Boolean.FALSE,pageable);
        if (!(questionPapers.isEmpty())){
            return questionPapers;
        }
        else {
            throw new QuestionPaperNotFoundException("no question paper has been approved yet ");
        }
    }

    public QuestionPaper addQuestionPaper(QuestionPaper questionPaper){
        String email = UserUtil.getUserAuthentication().getUsername();
        User user = userService.findByEmail(email);
        String questionPaperFingerprint;
        if (!user.getRole().equals("ROLE_TEACHER")){
            throw new UserNotAuthorizesException("User not Authorizes to make this request");
        }
        else {
            questionPaperFingerprint= QuestionPaperUtil.sha256(questionPaper.getListOfQuestion());
            if (questionPaperRepository.existsByQuestionPaperFingerprint(questionPaperFingerprint)){
                throw new DuplicateQuestionPaperException("one more question paper with exact questions exists");
            }
            else {
                questionPaper.setGeneratedBy(user);
                questionPaper.setApproved(Boolean.FALSE);
                questionPaper.setQuestionPaperFingerprint(questionPaperFingerprint);
                questionPaperRepository.save(questionPaper);
            }
        }
        return questionPaper;
    }

}