package com.FinalYearProject.FinalYearProject.Service;


import com.FinalYearProject.FinalYearProject.Domain.Question;
import com.FinalYearProject.FinalYearProject.Domain.QuestionPaper;
import com.FinalYearProject.FinalYearProject.Domain.User;
import com.FinalYearProject.FinalYearProject.Exceptions.QuestionPaperException.DuplicateQuestionPaperException;
import com.FinalYearProject.FinalYearProject.Exceptions.QuestionPaperException.QuestionPaperNotFoundException;
import com.FinalYearProject.FinalYearProject.Exceptions.UserEeceptions.UserNotAuthorizesException;
import com.FinalYearProject.FinalYearProject.Repository.QuestionPaperRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.stereotype.Service;

import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.Comparator;
import java.util.List;
import java.util.Set;

@Service
public class QuestionPaperService {
    @Autowired
    private QuestionPaperRepository questionPaperRepository;
    @Autowired
    private UserService userService;

    private List<QuestionPaper> getAllQuestionPapers(){
        List<QuestionPaper> questionPapers=questionPaperRepository.findAll();
        if (questionPapers.isEmpty()){
            throw new QuestionPaperNotFoundException("no question paper in db");
        }
        else {
            return questionPapers;
        }
    }

    public QuestionPaper findById(Long Id){
        return questionPaperRepository.findById(Id)
                .orElseThrow(()-> new QuestionPaperNotFoundException("no question paper with id"+Id));
    }

    public QuestionPaper findByExamTitle(String examTitle) {
        return questionPaperRepository.findByExamTitle(examTitle)
                .orElseThrow(()-> new QuestionPaperNotFoundException("no question paper with exam title"+examTitle));
    }

    public List<QuestionPaper> findByGeneratedByUsingEmail(String email){
        User user=userService.findByEmail(email);
        List<QuestionPaper> questionPapersGeneratedByUser=questionPaperRepository.findByGeneratedBy(user);
        if (questionPapersGeneratedByUser.isEmpty()){
            throw new QuestionPaperNotFoundException("no question paper has been generated by user with email "+email);
        }
        else {
            return questionPapersGeneratedByUser;
        }
    }

    public List<QuestionPaper> findByGeneratedByUsingId(Long Id){
        User user=userService.findUserById(Id);
        List<QuestionPaper> questionPapers=questionPaperRepository.findByGeneratedBy(user);
        if (questionPapers.isEmpty()){
            throw new QuestionPaperNotFoundException("no question paper has been generated by user with Id "+Id);
        }
        else {
            return questionPapers;
        }
    }

    public List<QuestionPaper> findByApprovedByUsingEmail(String email){
        User user=userService.findByEmail(email);
        List<QuestionPaper> questionPapers=questionPaperRepository.findByApprovedBy(user);
        if (questionPapers.isEmpty()){
            throw new QuestionPaperNotFoundException("no question paper has been generated by user with email "+email);
        }
        else {
            return questionPapers;
        }
    }

    public List<QuestionPaper> findByApprovedByUsingId(Long Id){
        User user=userService.findUserById(Id);
        List<QuestionPaper> questionPapers=questionPaperRepository.findByApprovedBy(user);
        if (questionPapers.isEmpty()){
            throw new QuestionPaperNotFoundException("no question paper has been generated by user with Id "+Id);
        }
        else {
            return questionPapers;
        }
    }

    public List<QuestionPaper> findApproved(){
        List<QuestionPaper> questionPapers=questionPaperRepository.findByApproved(Boolean.TRUE);
        if (questionPapers.isEmpty()){
            throw new QuestionPaperNotFoundException("no question paper has been approved yet ");
        }
        else {
            return questionPapers;
        }
    }

    public List<QuestionPaper> findNotApproved(){
        List<QuestionPaper> questionPapers=questionPaperRepository.findByApproved(Boolean.FALSE);
        if (questionPapers.isEmpty()){
            throw new QuestionPaperNotFoundException("no question paper has been left to approve");
        }
        else {
            return questionPapers;
        }
    }

    public QuestionPaper addQuestionPaper(QuestionPaper questionPaper){
        Authentication authentication= SecurityContextHolder.getContext().getAuthentication();
        String email = authentication.getName();
        User user = userService.findByEmail(email);
        String questionPaperFingerprint;
        if (!user.getRole().equals("ROLE_TEACHER")){
            throw new UserNotAuthorizesException("User not Authorizes to make this request");
        }
        else {
            questionPaperFingerprint=sha256(questionPaper.getListOfQuestion());
            if (questionPaperRepository.existsByQuestionPaperFingerprint(questionPaperFingerprint)){
                throw new DuplicateQuestionPaperException("one more question paper with exact questions exists");
            }
            else {
                questionPaper.setGeneratedBy(user);
                questionPaper.setApproved(Boolean.FALSE);
                questionPaper.setQuestionPaperFingerprint(questionPaperFingerprint);
                questionPaperRepository.save(questionPaper);
            }
        }
        return questionPaper;
    }

    private String sha256(Set<Question> questions) {
        try {
            // 1. Convert each question to a stable string representation
            String combined = questions.stream()
                    .sorted(Comparator.comparing(Question::getId)) // sort to make deterministic
                    .map(q -> q.getId() + "|" +
                            q.getSubjectName() + "|" +
                            q.getSubjectCode() + "|" +
                            q.getMappedCO() + "|" +
                            q.getCognitiveLevel() + "|" +
                            q.getQuestionMarks() + "|" +
                            q.getQuestionTitle() + "|" +
                            q.getQuestionBody() + "|" +
                            q.getInUse())
                    .reduce("",String::concat);
            System.out.println(combined);
            // 2. Hash the combined string
            MessageDigest md = MessageDigest.getInstance("SHA-256");
            byte[] hash = md.digest(combined.getBytes(StandardCharsets.UTF_8));

            // 3. Convert hash to hex
            StringBuilder hex = new StringBuilder();
            for (byte b : hash) {
                hex.append(String.format("%02x", b));
            }

            return hex.toString();

        } catch (NoSuchAlgorithmException e) {
            throw new RuntimeException(e);
        }
    }
}