package com.FinalYearProject.FinalYearProject.Exceptions.UserEeceptions;

/**
 * QuestionPaperNotFoundException - Exam Paper Lookup Exception
 * PURPOSE: Custom runtime exception thrown when a requested question paper cannot be found, indicating invalid paper reference or missing exam data.
 * EXCEPTION TYPE: Unchecked (RuntimeException) following Spring conventions for resource not found scenarios that should map to HTTP 404 responses.
 * TRIGGER CONDITIONS: Thrown when paper lookup by ID, title, or other identifier returns null. Used in QuestionPaperService methods like findById(), findByExamTitle(), etc.
 * ERROR HANDLING: Caught by global @ControllerAdvice exception handler and converted to HTTP 404 Not Found with appropriate error message for API consumers.
 * MESSAGE CONTENT: Should include identifying information - e.g., "Question paper with ID 789 not found" or "No paper found with title 'Final Exam 2023'".
 * USAGE CONTEXT: Used across supervisor and teacher controllers when accessing non-existent papers. Also in approval workflows when referenced paper is missing.
 * INTEGRATION: Extends RuntimeException for seamless Spring integration. Compatible with @ResponseStatus(HttpStatus.NOT_FOUND) for automatic status mapping.
 * RELATED SCENARIOS: Also covers empty result sets for filtered queries (e.g., "No approved papers found", "No papers generated by user@example.com").
 */
public class UnacceptableRequestException extends RuntimeException {
    public UnacceptableRequestException(String message) {
        super(message);
    }
}
