spring.application.name=FinalYearProject

#server config
#dynamic.local.ip=
#dynamic.public.ip=
logging.level.com.FinalYearProject=DEBUG
server.port=8080

# database config 
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Email configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${EMAIL_USERNAME:hassanrrafai5@gmail.com}
spring.mail.password=${EMAIL_PASSWORD:rsxyhxcjbeyfewtr}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#Error message
server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=always
