spring.application.name=FinalYearProject

# database config 
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:finalyearproject}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:yourNewPassword}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update

# Email configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${EMAIL_USERNAME:hassanrrafai5@gmail.com}
spring.mail.password=${EMAIL_PASSWORD:rsxyhxcjbeyfewtr}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#Error message
server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=always

#jwt config
