spring.application.name=FinalYearProject

#Error message
server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=always

#change profile
spring.output.ansi.enabled=ALWAYS
spring.profiles.active=dev