# for local testing

#server config
logging.level.com.FinalYearProject=DEBUG
app.version=/api/v1
server.port=8080

# database config
#TODO Use postgres cloud use https://console.aiven.io/account/a57e280766a5/project/hassanrafai1707-a49b/services
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:finalyearproject}
spring.datasource.username=postgres
spring.datasource.password=yourNewPassword
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
spring.thymeleaf.enabled=true

# Email configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=hassanrrafai5@gmail.com
spring.mail.password=rsxyhxcjbeyfewtr
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Redis configuration
# TODO user cloud like spring.data.redis.url=redis://default:dSfVm09Hep2ZjrDKxVU2yQxT5Htoxfvk@redis-12613.c330.asia-south1-1.gce.cloud.redislabs.com:12613
spring.data.redis.host=localhost
spring.data.redis.port=6379
